"""Adding delivery sources as concept

Revision ID: ea812cd3ab7b
Revises: ebdfd12fdade
Create Date: 2017-07-05 14:04:36.892758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea812cd3ab7b'
down_revision = 'ebdfd12fdade'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_sources',
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('batch', sa.Integer(), nullable=False, default=1),
    sa.PrimaryKeyConstraint('project_name', 'source_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_sources')
    ### end Alembic commands ###
